import java.security.SecureRandom;
import java.util.Scanner;
public class NumberGame {

	public static void main(String[] args) {
		System.out.println("TEAM DATA PIRATES");
		Scanner in=new Scanner(System.in);
		
		int[] x =new int[3] ;
		
		//x=random_code(10);
		int count;
		
		
		
		/*for(int i=0;i<3;i++) {
			System.out.print(x[i]);
		}
		System.out.println("");*/
		System.out.println("\t\t\t\t\t\t------'NUMBER GAME'------\n");
		System.out.println("This is a game where you will have to guess a three didit code which is generated by computer.\nRule for the game: Enter a 3 digit number in which each digits are unique");
		System.out.println("To guess the code you will get the following hints after each time you enter a number");
		System.out.println("\nHINTS:\n1.Match: One of the digit from user code matches with computer code with exact position.\n2.Close: One of the digit from user code matches with computer code but in the wrong position.\n3.None: None of the digits from user are present in the code");
		
		System.out.println("\nNow start guessing the code:\n");
		int input[]=new int[3];
		int attempt=0,digit;
		
		
			yes:
				while(true) {
					//x=random_code(10);
					int n=10;
					int[] a=new int[n];
					for(int i=0;i<n;i++) {
						a[i]=i;
					}
					int result[]=new int[n];
					int temp=n;
					SecureRandom rd=new SecureRandom();
					for(int i=0;i<n;i++) {
						int num=rd.nextInt(temp);
						result[i]=a[num];
						a[num]=a[temp-1];
						temp--;
					}
					
					
					
					for(int i=0;i<3;i++) {
						x[i]=result[i];
					}
			while(true) {
				digit=0;
				++attempt;
				String num=in.nextLine();
				for(int i=0;i<num.length();i++) {
					char ch=num.charAt(i);
					if(Character.isDigit(ch))
						digit++;
				}
				
				int flag1=0;
				if(digit!=num.length()) {
					flag1=1;
					
				}
				
				
				input=num.chars().map(i->i-'0').toArray();
				count=input.length;
				
				if(count==3) {
				
			
					int flag2=0;
					for(int i=0;i<3;i++) {
						for(int k=i+1;k<3;k++) {
							if(input[i]==input[k]) {
								flag2=1;
						
						
							}
						}
					}
					if(flag1==1 && flag2==1) System.out.println("Please enter number codde");
					else if(flag1==1 || flag2==1 ) {
						if(flag1==1)
							System.out.println("Please enter number codde");
						if(flag2==1)
							System.out.println("Please enter unique digits");
						//continue;
					}	
					else {
						
						int match=0,close=0,i,j;
						
						for(i=0;i<3;i++) {
							for(j=0;j<3;j++) {
								if(input[i]==x[j]) {
									if(i==j) match++;
									else close++;
								}
							}
						}
						if(match==3) {
							System.out.println("\n*************************\n|                       |\n|  *SUCCESS! YOU DID IT*  :)\n|                       |\n*************************");
							System.out.println("Totl number of attempts:"+attempt);
							System.out.println("\nTo play again Y/y.\nOr to quit the game press any other key.\n");
							char p=in.next().charAt(0);
							if(p=='Y' || p=='y') {
								attempt=0;
								System.out.println("\nStart guessing the code\n");
								num=in.nextLine();
								continue yes;
							}
							else {
								System.out.println("You ended the game");
								System.exit(0);
							}
							
							
						}
						else if(match>0 && match<3) {
							for(i=0;i<match;i++)
								System.out.println("Match");
						}
						
						if(close>0) {
							for(i=0;i<close;i++)
								System.out.println("close");
						}
						
						if(match==0 && close==0) System.out.println("None");
				
					}
				
				}
			
			
				else 
					System.out.println("Please enter a 3 digit code");
				
			
				//System.out.println("Number of attempts:"+(++j));
				
			}
			
		}	
	}

}
